totten/civix

src/CRM/ClientBundle/ClientFactory.php
I didn't dig through the rest of the codebase to see which other `getcwd()`'s it might be appropriate to replace with `exec("pwd")`'s, but this seems to work.
=> Fixes #45 by giving civix the non-dereferenced path to the extension.

src/CRM/CivixBundle/Command/TestRunCommand.php
I added a couple of additional options that can be passed to the civix test
command to make it easier to run and debug tests.
The first thing I did was make the Test Class argument optional because...
I needed a way to run all of the test classes for my extension at once and
couldn't find a good way to do this as currently implemented. So, I added a
--configuration option that will use PHPUnit's --configuration option to run
the tests as defined in a phpunit.xml file in the root of the extension.
I also added a --debug option as I've found the output with that option
incredibly helpful for tracking long test runs.
Finally, I added --colors option as I like the color output for an immediate
notification of pass or failure for the test run.
=> Additional features for the civix test command.

src/CRM/ClientBundle/ClientFactory.php
This fixes Drupal bootstrap for installs where the base URL is not the
root of the host. (Such as https://example.com/dcivi/ rather than just
https://example.com/ )
=> Fix regex extracting hostname from base URL

src/CRM/CivixBundle/Command/InfoGetCommand.php
according to symfony docs its impossible to have a "required" option
(if user specifies the option then it is possible to require a value)
the way around this seems to be to use an "argument"...
I'm assuming that we wouldn't be keen to alter the signature now - but this patch at leasts give more useful output (i was getting a couple of pages of stack trace with `civix info:get `)
hope this is helpful!
=> prevent untidy warning when xpath missing

src/CRM/CivixBundle/Resources/views/Code/module.civix.php.php
At this point in time, I think it makes sense to presume that managed entities are defined using api3.
Please merge if you agree :)
=> define managed entities with api3 by default

src/CRM/CivixBundle/Command/AddAngularPageCommand.php
Clarify that an Angular module must be generated first
https://civicrm.stackexchange.com/questions/18837/unknown-path-when-viewing-a-newly-generated-angular-page
=> generate:angular-page - improve help text

UPGRADE.md, src/CRM/CivixBundle/Resources/views/Code/api.php.php, src/CRM/CivixBundle/Resources/views/Code/entity-api.php.php, src/CRM/CivixBundle/Resources/views/Code/entity-bao.php.php, src/CRM/CivixBundle/Resources/views/Code/form.php.php, src/CRM/CivixBundle/Resources/views/Code/module.civix.php.php, src/CRM/CivixBundle/Resources/views/Code/module.php.php, src/CRM/CivixBundle/Resources/views/Code/page.php.php, src/CRM/CivixBundle/Resources/views/Code/report.php.php, src/CRM/CivixBundle/Resources/views/Code/search.php.php, src/CRM/CivixBundle/Resources/views/Code/test-e2e.php.php, src/CRM/CivixBundle/Resources/views/Code/test-headless.php.php, src/CRM/CivixBundle/Resources/views/Code/test-legacy.php.php, src/CRM/CivixBundle/Resources/views/Code/upgrader-base.php.php, src/CRM/CivixBundle/Resources/views/Code/upgrader.php.php
Civi's `ts()` function (PHP) works with extensions, but it's cumbersome to do it correctly -- you have to include the `domain` parameter, and many people aren't aware of this (or do it inconsistently).
(_Update_: Similar usability issues affect `CRM_Core_Resources::singleton()->getUrl()` and `CRM_Core_Resources::singleton()->getPath()`.)
== Before ==
Code generated by `civix` directly calls the `ts()` function, but it's fairly inconsistent/unreliable about passing the `domain`.
== After ==
* The autogenerated helper file (`mymodule.civix.php`) defines a helper class `CRM_Mymodule_ExtensionUtil`.
* The expression `use CRM_Mymodule_ExtensionUtil as E;` is included in all other autogenerated PHP files.
* The `E`  class supports several helpers. Many of these functions were available before, …
=> Define and use `E::ts()` helper function (etal)

src/CRM/CivixBundle/Command/BuildCommand.php
This should reduce the size of generated extension zips.
Refs #103.
=> Do not bundle the .git directory in extension downloads.

UPGRADE.md
The UPGRADE.md had separate sections for different topics (such as "hooks" and "tests), and each topic had a list of special, version-specific upgrade tasks.
If you're upgrading after a while, it's hard to tell which sections to read. Using a more chronological order should help.
=> UPGRADE.md - Consolidtate general notes. Sort special tasks chronologically.

src/CRM/CivixBundle/Application.php, src/CRM/CivixBundle/Builder/Collection.php, src/CRM/CivixBundle/Builder/CopyClass.php, src/CRM/CivixBundle/Builder/License.php, src/CRM/CivixBundle/Builder/PHPUnitGenerateInitFiles.php, src/CRM/CivixBundle/Builder/PhpUnitXML.php, src/CRM/CivixBundle/Command/AbstractAddPageCommand.php, src/CRM/CivixBundle/Command/AddAngularDirectiveCommand.php, src/CRM/CivixBundle/Command/AddAngularModuleCommand.php, src/CRM/CivixBundle/Command/AddAngularPageCommand.php, src/CRM/CivixBundle/Command/AddApiCommand.php, src/CRM/CivixBundle/Command/AddCaseTypeCommand.php, src/CRM/CivixBundle/Command/AddCustomDataCommand.php, src/CRM/CivixBundle/Command/AddEntityCommand.php, src/CRM/CivixBundle/Command/AddReportCommand.php, src/CRM/CivixBundle/Command/AddSearchCommand.php, src/CRM/CivixBundle/Command/AddTestCommand.php, src/CRM/CivixBundle/Command/AddUpgraderCommand.php, src/CRM/CivixBundle/Command/BuildCommand.php, src/CRM/CivixBundle/Command/ConfigGetCommand.php, src/CRM/CivixBundle/Command/ConfigSetCommand.php, src/CRM/CivixBundle/Command/InfoGetCommand.php, src/CRM/CivixBundle/Command/InfoSetCommand.php, src/CRM/CivixBundle/Command/InitCommand.php, src/CRM/CivixBundle/Command/PingCommand.php, src/CRM/CivixBundle/Command/TestRunCommand.php, src/CRM/CivixBundle/Services.php, src/CRM/CivixBundle/Utils/Path.php
This is extracted from #115. It only impacts the civix logic -- it does *not* change any of the templates.
To test, I used `tests/make-example.sh` (as described in README.md) to ensure that the `civix` outputs the same code before and after the patch.
=> Use pretty array syntax in civix logic

box.json
The README should embed a placeholder for a screenshot.  This worked
correctly with a git-based copy of `civix`, but `civix.phar` didn't have the
file, leading it to malfunction.  Adding the file fixes it.
=> box.json - Include `images/placeholder.png`

UPGRADE.md, src/CRM/CivixBundle/Resources/views/Code/phpunit-boot-cv.php.php
There was add an odd phenomenon when an extension is moved to a symlinked dir, e.g.
```
ln -s ~/src/org.example.foo civicrm/tools/extensions/org.example.foo
```
If you navigated into the folder and called `cv` directly (e.g.  `cv api contact.get` or `cv php:boot`), then it worked fine.  However, if you navigated into the same folder and called `phpunit` (which then called `cv php:boot`), then they'd fail. Empirically, `phpunit` does the equivalent of `chdir(realpath(getcwd()))` (although I haven't traced how/why).
This patch provides a work-around in the template. You may need to update the `tests/phpunit/bootstrap.php` to benefit from it.
=> phpunit bootstrap - Work-around for issues with running phpunit in symlinked dirs

src/CRM/CivixBundle/Command/AddFormCommand.php, tests/make-example.sh
Hi again,
I am surprised this has slipped through undetected/reported. Maybe I am missing something but I think this was a bug / is a fix:
**Before:**
```
buildkit@civicrm:~/build/chatbot/sites/all/modules/civicrm/tools/extensions/civicrm-chatbot$ civix generate:form Admin_Facebook civicrm/admin/chat/facebook
...
Write /buildkit/build/chatbot/sites/all/modules/civicrm/tools/extensions/civicrm-chatbot/templates/CRM/Chatbot/Form/Admin_Facebook.tpl
```
**After**
```
buildkit@civicrm:~/build/chatbot/sites/all/modules/civicrm/tools/extensions/civicrm-chatbot$ civix generate:form Admin_Facebook civicrm/admin/chat/facebook
Write /buildkit/build/chatbot/sites/all/modules/civicrm/tools/extensions/civicrm-chatbot/templates/CRM/Chatbot/Form/Admin/Facebook.tpl
```
=> Bug in form template path

src/CRM/CivixBundle/Application.php, src/CRM/CivixBundle/Builder/Module.php, src/CRM/CivixBundle/Command/AddDaosCommand.php, src/CRM/CivixBundle/Command/AddEntityBoilerplateCommand.php, src/CRM/CivixBundle/Command/AddEntityCommand.php, src/CRM/CivixBundle/Command/InitCommand.php, src/CRM/CivixBundle/Resources/views/Code/module.civix.php.php, src/CRM/CivixBundle/Resources/views/Code/module.php.php, tests/make-example.sh
Hey there,
Automatically creating DAO files and the associated SQL statements for install / uninstall has been missing from civix for a while. It is a pain to do this manually: (step 4 of https://docs.civicrm.org/dev/en/latest/extensions/civix/#generate-entity).
This PR adds a new command `civix generate:daos` to automate that step.
The expected workflow is that you have run `civix generate:entity` 1 or more times to generate entities, and have edited the schema xml files to your liking. You then run `civix generate:daos` which generates DAOs and creates auto install / uninstall sql for the extension as a whole.
The approach I took was to reuse the bare minimum from `CRM_Core_CodeGen_*` rather than try do it the civix way. It is admitedly a bit hacky, and I would understand if there were …
=> new command to generate boilerplate from XML schema file

src/CRM/CivixBundle/Command/AddEntityCommand.php, src/CRM/CivixBundle/Utils/Naming.php, src/CRM/CivixBundle/Utils/NamingTest.php
`civix generate:entity ChatUser`
Previously made table names like `civicrm_chatuser`
Now makes table names like `civicrm_chat_user`
=> generate:entity - Table name should be in camel-case

src/CRM/CivixBundle/Resources/views/Code/module.civix.php.php
The lines moved are meaningless unless moved per this PR (arguably they should be removed or the function that uses these determines the version, but if they are there they should be right)
=> Fix non-sensical variable setting

src/CRM/CivixBundle/Resources/views/Code/module.civix.php.php
Order is important when managing entities: one must create dependencies before creating dependent entities. Custum groups need to be created before custom fields, option groups before option values, etc.
One way of doing this is to ensure that dependencies appropriate order in the same file. This breaks down if dependencies are split across files.
Alphabetically sorting the managed files before including them allows one to define managed entities like this
```
managed
├── 01-ContactType.mgd.php
├── 05-CustomGroup.mgd.php
└── 06-CustomField.mgd.php
```
Aside: a more sophisticated `CRM_Core_ManagedEntities` might be cleverer about trying to 'satisfy dependencies' before giving up ( [something like this](https://gist.github.com/michaelmcandrew/21754058092bfd63504490f59ae19944)) but in the …
=> order mgd files before including

src/CRM/CivixBundle/Resources/views/Code/module.civix.php.php
The use of static caching in this function is unhelpful for tests & we get the same
benefit by moving the in_array check to before the
is_dir check - meaning we won't do a file check unless it is not present
(Just found this patch locally & realised it must have been written when agreed in #139 but never opened - @totten I can't merge to this repo)
=> #139 Improve alterSettingsFolders hook.

src/CRM/CivixBundle/Resources/views/Code/module.civix.php.php
_bla_civix_insert_navigation_menu only takes 3 params; don't call it with 4
=> Remove extra function parameter when inserting submenus

src/CRM/CivixBundle/Resources/views/Code/module.civix.php.php
- fix array syntax (array() => [])
- brings comment block formatting closer to drupal standard (higher level than we enforce)
- adds a missing return tag
- replaces a CRM_Core_Fatal with throwing an exception - we've been doing this pretty aggressively in core so probably time to do here too. Bonus, it's in a function that says 'Note: This hook only runs in CiviCRM 4.4+.' and should probably be removed anyway by now
=> Style cleanup

src/CRM/CivixBundle/Resources/views/Code/api.php.php
@totten  a little more cleanup
- array syntax
- comment block tidying
- we don't really recommend error codes so removed that
- we don't return civicrm_api3_create_error so removed that too
=> Api file cleanup

src/CRM/CivixBundle/Resources/views/Code/entity-api.php.php
@totten and another one 
- comment blocks closer to full drupal spec (we don't enforce it all but for templates....)
- pass the entity name to create & get. This is pretty important as you MUST do this if you want to enable custom data for your api (you also need to add an option value). This removes a trap for young players
=> Fix up entity api template

UPGRADE.md, src/CRM/CivixBundle/Builder/Info.php
APIv4 looks for classes in the `Civi\Api4` namespace and `Civi/Api4` folder.  To support generation of APIv4 code, the `info.xml` should have a corresponding classloader:
```xml
<classloader>
<psr4 prefix="Civi\" path="Civi" />
</classloader>
```
This revision:
* Includes the default on new modules
* Adds a note for people updating existing modules
=> Builder\Info - Generate '<classloader>/<psr4>' to support APIv4

src/CRM/CivixBundle/Command/AddEntityBoilerplateCommand.php
This fixes the issue by calling `file_put_contents` instead of... well... *not* calling `file_put_contents`.
=> Fix #172: SQL files not written by generate:entity-boilerplate

src/CRM/CivixBundle/Command/InfoSetCommand.php
ping @totten this fixes a bug in the mosaico build process as shown by https://test.civicrm.org/view/Tools/job/Tool-Publish-mosaico/125/console I copied across a patched phar version to bknix-old as publisher and confirmed it fixed the build job as per https://test.civicrm.org/view/Tools/job/Tool-Publish-mosaico/126/
=> Ensure that using civix info:set -x version -t xxx generates valid xml

src/CRM/CivixBundle/Resources/views/Code/module.civix.php.php
Using {} for array or string offsets is deprecated in PHP7.4 ping @totten https://stackoverflow.com/questions/59158548/array-and-string-offset-access-syntax-with-curly-braces-is-deprecated
=> Update civix file to be complient with PHP7.4

src/CRM/CivixBundle/Resources/views/Code/upgrader-base.php.php
I don't think this line gets called much, but when doing a grep every extension that has an upgrader shows up. I haven't tested this - I guess it comes up if you try to update a really old extension.
=> Convert deprecated function CRM_Core_BAO_Setting::getItem

src/CRM/CivixBundle/Builder/Module.php, src/CRM/CivixBundle/Resources/views/Code/module.civix.php.php
This fixes our formatting issue with generated entity types (using old array(), extraneous space).
I have tested with no entities, 1 entity & 2
=> Update array formatting on generated entityTypes

bin/civix, composer.json, composer.lock, src/CRM/CivixBundle/Builder/PhpData.php
Before
--------
Generated php files such as `*.ang.php` would not look so great, with bad indentation and old array syntax.
After
------
Should look much better.
=> Update PHP. Use symfony varExporter for prettier output

README.md
Was still pointing to the wiki, now goes to the docs
=> fix the link to the documentation

src/CRM/CivixBundle/Resources/views/Code/upgrader-base.php.php
@totten This fixes an issue with the upgrader when run via a core extension - found through eventcart - https://github.com/civicrm/civicrm-core/pull/17339/commits/ad331419797b6071e64d340dd5ca72ad713cc3af
Use the `E::path()` helper to get the path of the extension instead of relying on parent parent parent of current dir..
Also one typo in variable definition.
=> Use helper function to get extension directory path

src/CRM/CivixBundle/Resources/views/Code/module.civix.php.php
… 
Results in
const SHORT_NAME = 'deduper';
Not
const SHORT_NAME = "deduper";
=> Use single quotes in output as it is best practice to use double only when needed

src/CRM/CivixBundle/Command/AddEntityBoilerplateCommand.php
Overview
----------
Cleans up the "generated from" comment in each DAO file to start from the extension rather than what is often the developer's home directory.
Before
-----------
Comment says `Generated from /home/colemanw/bknix/build/d7/web/sites/default/files/civicrm/ext/org.civicrm.volunteer/xml/schema/CRM/Volunteer/Project.xml`
After
-----------
Comment says `Generated from org.civicrm.volunteer/xml/schema/CRM/Volunteer/Project.xml`
=> Normalize path to xml file in generated DAO files

src/CRM/CivixBundle/Command/AddEntityCommand.php, src/CRM/CivixBundle/Resources/views/Code/entity-api3-test.php.php
This improves test-coverage for APIv3 entities in two ways:
* The command `generate:entity` will create a file `tests/phpunit/api/v3/MyEntityTest.php`.
* The QA script `bash tests/make-example.sh` calls `generate:entity` and subsequently runs `phpunit` on all generated tests. Therefore, it runs
This is motivated by #193, which revealed that `generate:entity` regressed in two ways circa 19.10. I've confirmed that this unit-test would complain about both of the problems.
I've only added the patch for APIv3 (b/c that had the last bug), but an APIv4 patch should look pretty similar and is patch-welcome.
Ping @twomice @eileenmcnaughton @colemanw
=> AddEntityCommand - Generate APIv3 unit-test

src/CRM/CivixBundle/Command/AddApiCommand.php, src/CRM/CivixBundle/Resources/views/Code/test-api.php.php, tests/make-example.sh
The proximate reason for change -- `tests/make-example.sh` was using CamelCase actions, and it passed on macOS, but it didn't pass on Linux. I'd like the test to give consistent output on both platforms.
It may be that there are semi-legit ways to get actions working with CamelCase and/or under_score_case, e.g.
* Use a file-name like `MyEntity/Myaction.php` but call it as `MyEntity, MyAction`. This seemed to work in one Linux trial for calling `MyAction`, but calls weren't interchangeable with `my_action`. 
* Don't generate standalone action files. Put all the actions into a combined per-entity file. However, this doesn't fit well into civix's   mental model of "call generator => produce well-defined PHP file".
I haven't re-tested these possiblities to be sure, but -- even if they work -- …
=> generate:api - Explicitly prefer singleword action names

src/CRM/CivixBundle/Resources/views/Code/readme.md.php
Buncles a few proposed changes to the default README:
* Require PHP 7.2 instead of 7.0, since that is what CiviCRM core recommends
* Cut the installation instructions and refer to the sysadmin guide instead
* Replace "Usage" with "Getting Started" as per https://lab.civicrm.org/extensions/extensions-directory/-/issues/18
=> extensions/extensions-directory#18 Update the boilerplate README

src/CRM/CivixBundle/Resources/views/Code/module.civix.php.php
As per https://github.com/totten/civix/issues/206
=> remove old backward compatibility code that generates deprecation warnings

src/CRM/CivixBundle/Resources/views/Code/entity-schema.xml.php
Metadata-based UIs like Search Kit can use these `<html><type>` tags to render the field appropriately.
=> Add type=Number to id field in generated schema

src/CRM/CivixBundle/Resources/views/Code/phpunit-boot-cv.php.php
Other minor fixups to preferred php (as per inspections) which I opened this to demonstrate https://github.com/civicrm/civicrm-core/pull/19834
=> Remove safe-mode as it is php5.4

composer.json, composer.lock
cv version .2 doesn't work with php 7.4 is the main thing, but also why not.
I'd updated composer.json locally a long time ago for something else that wasn't working - completely forgot about that so I can't say what it was.
e.g. https://civicrm.stackexchange.com/questions/38061/getting-error-when-using-civix-generatemodule-or-civix-generateentity-curly-br
=> Update cv to ~0.3

phpunit.xml.dist, src/CRM/CivixBundle/Builder/PhpUnitXML.php
as per https://github.com/civicrm/civicrm-core/pull/20356 and https://stackoverflow.com/questions/55091768/what-is-phpunit-result-cache
ping @eileenmcnaughton @totten
=> Do not generate cache result file in phpunit8

src/CRM/CivixBundle/Command/InitCommand.php, src/CRM/CivixBundle/Utils/Naming.php, tests/make-example.sh
Previously the command `civix generate:module "search_kit"` would throw `'Malformed package name'`
Note: I moved the `-` character to the beginning of each `[]` block for readability; dashes do not need to be escaped if they are the first character.
=> Allow underscores in module names

UPGRADE.md, src/CRM/CivixBundle/Builder/Info.php, src/CRM/CivixBundle/Command/AddAngularDirectiveCommand.php, src/CRM/CivixBundle/Command/AddAngularModuleCommand.php, src/CRM/CivixBundle/Command/AddAngularPageCommand.php, src/CRM/CivixBundle/Command/InitCommand.php
This is a followup to #227, which allows use of `_` in module-names. If you have underscore names and then generate Angular code, the module names are peculiar. This updates the naming convention. Below, I've reproduced the explanation from `UPGRADE.md`:
ping @colemanw 
--
When generating Angular code, the default Angular module name has traditionally matched the extension's short-name, eg
| __Long Name (Key)__ | __Short Name (file)__ | __Default Angular Module__ |
| -- | -- | -- |
| `org.example.foobar` | `foobar` | `foobar` |
| `org.example.foo-bar` | `foo_bar` | `foo_bar` (!!) |
This has two problems:
* If the extension has dashes or underscores, then the Angular module winds up with underscores. Underscores
do not map sensibly to HTML tags or attributes.
* There is no standard prefix. …
=> Angular - Default module-name should be well-defined in an `_`-world

.gitignore, box.json, composer.json, composer.lock, src/CRM/CivixBundle/Command/AbstractCommand.php
This is a follow-up to #222 and #230 which:
* Fixes the regression with interactive prompts. (Symfony 3+ eliminated the "dialog" helper and added the "question" helper.)
* Tightens up the Symfony constraints. v2-v5 is really wide. Just do Symfony 4+. (Note that `civix` now requires PHP 7.1+ and that it generally uses php-scoper.)
* Relaxes the dependency tree - instead of requiring `civicrm/cv` and all its transitive deps (psysh etal), we download the single file required from `civicrm/cv`. This reduces overall download significantly (eg ~900k in the final PHAR) and should make it a bit easier to twiddle deps.
=> composer.json - Multiple dependency revisions

src/CRM/CivixBundle/Resources/views/Code/module.civix.php.php
I'm getting notices about this line
```
$template = & CRM_Core_Smarty::singleton();
```
PHP Notice:  Only variables should be assigned by reference in /srv/civi-sites/wmff/civicrm/ext/greenwich/greenwich.civix.php on line 94
__DIR__ is just a teensy bit shorter / more readable
=> Update config function

src/CRM/CivixBundle/Command/InitCommand.php
=> InitCommand - If the new `key` and `<file>` don't match, prompt for confirmation

composer.json, composer.lock
It appears there was an undeclared dependency on `symfony/filesystem` -- the
dependency was previously included indirectly and then unintentionally
removed (probably by [1f9d24bcf40c998756d905ac698757b4c4526bd2](https://github.com/totten/civix/commit/1f9d24bcf40c998756d905ac698757b4c4526bd2#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34L8-R8)).
=> Fix regression in `AddCodeceptionConfigCommand`

README.md, box.json, composer.json, composer.lock, mixin-backports.php, phpunit.xml.dist, src/CRM/CivixBundle/Builder/Info.php, src/CRM/CivixBundle/Builder/Mixins.php, src/CRM/CivixBundle/Command/UpgradeCommand.php, src/CRM/CivixBundle/ComposerCompile.php, src/CRM/CivixBundle/Resources/views/Code/module.civix.php.php, src/CRM/CivixBundle/Upgrader.php, src/CRM/CivixBundle/Utils/NamingTest.php, src/CRM/CivixBundle/Utils/Path.php, tests/bootstrap.php, tests/e2e/AddPageTest.php, tests/e2e/CivixProjectTestTrait.php, tests/e2e/MixinMgmtTest.php
Overview
----------
Broadly, this is an optimization which will omit `mixin/*` files that are already in `civicrm-core`.
Before
-------
`civix` unconditionally copies any mixins that it relies into the `mixin` folder (for each extension).
But, depending on the extension's planned deployment/usage, it may not need the files.
When updating a core-ext, this feels particularly gratuitous. The same mixins are already in core... we don't need 5 more copies in the same repo...
After
-----
`mixin`s are copied conditionally. Example: `civix generate:page` requires `menu-xml@1.0.0`. This mixin was merged into `civicrm-core@5.45`. The `menu-xml` file _might_ be copied into an extension, depending:
* If the extension targets `<compatibility><ver>5.45</ver></compatibility>`, then it _does not_ need to …
=> Mixins - Use `<compatibility>` to enable/disable backporting

src/CRM/CivixBundle/Upgrader.php, src/CRM/CivixBundle/Utils/EvilEx.php, tests/e2e/CleanEmptyTest.in.txt, tests/e2e/CleanEmptyTest.out.txt, tests/e2e/CleanEmptyTest.php, upgrades/22.05.2.up.php
I grepped `universe` for examples of bespoke hook-implementations. There weren't a huge number, but there were a couple things like:
* Multiple extensions had comments into the boilerplate for `hook_angularModules`.  (Probably an older template?) The comments prevented it from recognizing the functions as empty.
```php
function foo_civicrm_angularModules(...) {
// Yadda yadda
}
```
* Multiple extensions had a `return` in the boilerplate for `hook_managed`.  (Probably an older template?) These were being left behind and liable to duplicate the `mgd-php` behavior.
```php
function foo_civicrm_managed(...) {
return _foo_civix_civicrm_managed(...);
}
```
* Multiple extensions had an identical chunk in `hook_alterSettingsFolders`.  (Probably an older template?)  These were being left behind and …
=> Upgrade - Fix cleanup logic for a few funny edge-cases

src/CRM/CivixBundle/Command/InitCommand.php
This is probably worthwhile because we're getting more processes that use mgd-php, and (for now) it's fairly simple.
=> InitCommand - Enable mgd-php by default

src/CRM/CivixBundle/Builder/Mixins.php, src/CRM/CivixBundle/Command/MixinCommand.php, src/CRM/CivixBundle/Services.php, tests/e2e/MixinMgmtTest.php
Consider this command:
```
civix mixin --enable-all
```
On  git-based deployments, it worked. But on phar-based deloyments, it didn't.
The problem is that `--enable-all` needs a list of backports, which was retrieved via `Mixlib::getList()` and `glob()` (*which doesn't work in PHAR folders*). Getting the same list from `mixin-backports.php` circumvents the `glob()` limit.
=> MixinCommand - Fix '--enable-all' on PHAR builds

src/CRM/CivixBundle/Resources/views/Code/phpunit-boot-cv.php.php
To run unit tests that do not require a CiviCRM environment the extension's classes need to be loadable by the class loader.
It might be considered to do this for every extension in case the extension under test is in the `ext` directory so that it is possible to access classes of other extensions.
=> Add extension dirs to class loader in bootstrap.php template

upgrades/16.10.0.up.php
Extensions going from (say) v15.* to v22.05 should add `hook_postInstall` (as in `16.10.0.up.php`)... unless they have been manually edited to use `<upgrader>`.
CC @colemanw 
See: https://github.com/totten/civix/issues/221#issuecomment-1157599835
=> upgrades/16.10.0.up.php - Don't add hook_postInstall if `<upgrader>` registered via XML

src/CRM/CivixBundle/UpgradeList.php
Notably, this skips backup files like `*~ or `*.bak`
=> UpgradeList - Only check files that end in '.up.php'

src/CRM/CivixBundle/Builder/Info.php, src/CRM/CivixBundle/Command/AbstractAddPageCommand.php, src/CRM/CivixBundle/Command/AbstractCommand.php, src/CRM/CivixBundle/Command/AddAngularDirectiveCommand.php, src/CRM/CivixBundle/Command/AddAngularModuleCommand.php, src/CRM/CivixBundle/Command/AddAngularPageCommand.php, src/CRM/CivixBundle/Command/AddApiCommand.php, src/CRM/CivixBundle/Command/AddCaseTypeCommand.php, src/CRM/CivixBundle/Command/AddCustomDataCommand.php, src/CRM/CivixBundle/Command/AddEntityBoilerplateCommand.php, src/CRM/CivixBundle/Command/AddEntityCommand.php, src/CRM/CivixBundle/Command/AddReportCommand.php, src/CRM/CivixBundle/Command/AddSearchCommand.php, src/CRM/CivixBundle/Command/AddTestCommand.php, src/CRM/CivixBundle/Command/AddThemeCommand.php, src/CRM/CivixBundle/Command/AddUpgraderCommand.php, src/CRM/CivixBundle/Command/BuildCommand.php, src/CRM/CivixBundle/Command/MixinCommand.php, src/CRM/CivixBundle/Command/UpgradeCommand.php
There have been multiple reports (Github, MM, etc; ex) where an extension gets into a non-runnable state due to a workflow/communication issue. (Ex: #244, #250, #252) There is a common thread to these:  the `civix upgrade` steps need to run. A typical example flow might be:
1. Install latest version of `civix`
2. Checkout a pre-existing extension (*esp one which pre-dates `civix` v22.05*)
3. Run any code-generating command (`generate:page`, `generate:api`, `generate:entity-boilerplate`, etc).
* As a side-effect, this regenerates `*.civix.php` from the latest template. Critically, it it does not update any inter-related files (like `info.xml` or the main `*.php` file).
4. Open some Civi screen and observe an error (eg *undefined function `_mymodule_civix_civicrm_alterSettingsFolders()`*). …
=> All code-generator commands should validate the current format/version

src/CRM/CivixBundle/Command/AddEntityCommand.php, src/CRM/CivixBundle/Command/UpgradeCommand.php, src/CRM/CivixBundle/Upgrader.php, tests/e2e/CivixProjectTestTrait.php, tests/e2e/IdempotentUpgradeTest.php
Add an option to  `civix upgrade`  which allows you to replay the upgrade checks, eg
```
civix upgrade                ##  Default: Run upgrade based on the saved version from info.xml
civix upgrade --start=0      ##  Run all upgrade steps from the beginning of time.
civix upgrade --start=22.01  ##  Run upgrade steps from 22.01 to current.
```
This generally shouldn't be necessary, but there could be edge-cases where it's useful. (*Speculating...*) For example, if you merge branches from different developers with different civix versions, then you may want to replay an upgrade on the final branch.
Inspired by comments from  @artfulrobot in #252.
=> civix upgrade - Add option to replay previous upgrade steps

src/CRM/CivixBundle/Resources/views/Code/module.civix.php.php, src/CRM/CivixBundle/Resources/views/Code/module.php.php
php is getting tighter & tigher on type hints & I think it's pretty likely that by the
time we are doing php9 they we will be doing re-work to add them - so
we should make sure we are adding them on code as we go now. This just adds
a handful of easy ones (ones where it is really easy to see what the hints
should be)
=> Add some (easy) return type hints

src/CRM/CivixBundle/Resources/views/Code/entity-api3-test.php.php, src/CRM/CivixBundle/Resources/views/Code/entity-bao.php.php, src/CRM/CivixBundle/Resources/views/Code/test-api.php.php, src/CRM/CivixBundle/Resources/views/Code/test-headless.php.php, src/CRM/CivixBundle/Resources/views/Code/upgrader-base.php.php, src/CRM/CivixBundle/Resources/views/Code/upgrader.php.php
I recently submitted a civix-generated extension & found man boilerplate lines didn't pass style - this fixes.
It also removes a 'not-a-word' 'myinstall' & switches to 'my_install' - we shouldn't make people have to add made-up words to their IDE spelling checkers...
https://github.com/civicrm/civicrm-core/pull/24585
=> Standards fixes in civix

src/CRM/CivixBundle/Builder/Info.php, upgrades/22.10.0.up.php
This updates the `info.xml` in new extensions (`civix generate:module`) and existing extensions (`civix upgrade`) to declare:
```xml
<classloader>
<psr0 prefix="CRM_" path=""/>
</classloader>
```
Todo: Check test results
=> Add PSR-0 classloading for "CRM"

src/CRM/CivixBundle/Command/AddEntityBoilerplateCommand.php, tests/e2e/AddEntityTest.php
This fixes an issue where foreign keys referencing their own table trigger the check for circular dependencies. This can be avoided by ignoring affected foreign keys when ordering tables.
This also fixes a null reference in the error handler.
Note that I've only done limited testing (read: running `tests/e2e/AddEntityTest.php`) as I ran into an issue with `box` and ran out of time to work on this. 😅
=> Fix self-reference being identified as circular foreign key

src/CRM/CivixBundle/Command/InitCommand.php
I don't think anyone's developing on CiviCRM 4.2 anymore...
=> Remove old version check

src/CRM/CivixBundle/Builder/Info.php, src/CRM/CivixBundle/Command/AddUpgraderCommand.php, src/CRM/CivixBundle/Command/UpgradeCommand.php, src/CRM/CivixBundle/Resources/views/Code/module.civix.php.php, src/CRM/CivixBundle/Resources/views/Code/upgrader.php.php, src/CRM/CivixBundle/Upgrader.php
Since 5.38 core supports an `<upgrader>` tag in liu of hooks, and a common base class.
For extensions where core version is >= 5.38, this will generate upgrader classes that use the common base, and the tag instead of delegated hooks.
It will also perform this cleanup on existing modules during each `civix upgrade`.
=> Upgrade to use CRM_Extension_Upgrader_Base and info.xml `<upgrader>` tag

src/CRM/CivixBundle/Command/InitCommand.php, tests/e2e/CivixProjectTestTrait.php, tests/e2e/IdempotentUpgradeTest.php, tests/e2e/MixinMgmtTest.php
This does three related this:
1. Allow an option like `civix generate:module --compatibility=5.0`
2. Use a default value (`--compatibility=current`) which inherits the current version from the locally installed CiviCRM instance. (Presumably, that's the version you will actually test against...)
3. Update some of the E2E tests to explicitly control for the initial `--compatibility`. These tests examine how the code changes with different compatibility targets.
=> "generate:module" - Add option to specify compatibility of new modules. Use dynamic default.

scripts/load-snapshot.sh, scripts/make-snapshots.sh, src/CRM/CivixBundle/Command/AddUpgraderCommand.php, src/CRM/CivixBundle/Command/UpgradeCommand.php, src/CRM/CivixBundle/Resources/views/Code/module.civix.php.php, src/CRM/CivixBundle/Resources/views/Code/module.php.php, src/CRM/CivixBundle/Upgrader.php, upgrades/22.12.1.up.php
This is a follow-up/re-roll to the recent #270. Its main purpose is to fix the regression where new extensions have mis-linked stubs. The approach is to go all-in on 5.38-style `<upgrader>` classes -- but to preserve the edifice needed for mixin-polyfill.
If you have an extension that targets `5.0` and defines `CRM_*_Upgrader`, then `civix upgrade` will produce this:
The message gets simpler in other circumstances -- e.g.
* If you don't have `CRM_*_Upgrader`, then some of the bullets go away.
* If you don't have `CRM_*_Upgrader`, or if you already require 5.38+, then the warning goes away.
* `CRM_*_Upgrader`
* (**Invariant condition for v22.12**) `CRM_*_Upgrader` requires CiviCRM v5.38.
* If you have an extension which already uses `CRM_*_Upgrader`, then `civix upgrade` will update …
=> Reinstante lifecycle hooks (partially). Always uses 5.38-style `<upgrader>`.

mixin-backports.php, tests/e2e/MultiExtensionTest.php
The test creates two extensions. I've run it on 5.44 (which requires the polyfill). The test fails with the old revision of the polyfill -- and passes with @jaapjansma's updated revision. Woot.
=> Apply update polyfill. Add test coverage for generating multiple extensions. (#257)

src/CRM/CivixBundle/Builder/Mixins.php, tests/e2e/CivixProjectTestTrait.php, tests/e2e/MixinMgmtTest.php
If you activate a mixin that declares `minimum => 5.45`, then your `info.xml` should require at least `5.45.`
The update should manipulate `<compatibility>` automatically across a range of commands/use-cases. It will show messages about when+why it changes `<compatibility>`.
(*It might be nicer to prompt for confirmation, but -- in this case -- it takes more work than it's worth. And anyone who uses `git` will still have an extra opportunity to consider the change.*)
For nerding purposes, here are a few examples/edge-cases of how `<compatibility>` is updated:
* `civix mixin --enable=menu-xml@1.0.0`
* __Description__: The mixin requires `minimum=>5.27`. Enabling it will cause the `<compatibility>` constraint to go up to `<ver>5.27</ver>`. (If you already require 5.27+, then the requirement …
=> Mixins - When toggling mixins, auto-raise the the `<compatibility>` flag.

src/CRM/CivixBundle/Resources/views/Code/module.civix.php.php
On trying to upgrade some extensions `addTemplateDir` actions I was struck by how many of the extensions are adding template directories that don't exist. I feel like this must be at least marginally worse for performance & it feels a bit confusing
@totten
=> Only add templates dir if it exists

upgrades/23.02.1.up.php
Overview
-------------
On Mattermost, it came up that folks often get tripped-up when their existing extension doesn't have the `Civi` namespace turned on.
This PR adds an upgrade-step to turn it on:
Comments
--------------
For many authors with existing extensions, it's probably better to enable this proactively. It's a bit obscure, and it's already enabled by default on new extensions. If you omit this and need it, then it can take an hour of debugging to figure out why classes don't load.
Still, this is not strongly required.  Many existing extensions work fine without it.  There's a small performance argument for keeping it disabled if you don't need it.
So this update presents the option.  Even if the developer say no, it should at least promote some consciousness about classloading …
=> upgrades/23.02.1 - Suggest enabling the "Civi" namespace

mixin-backports.php
Should fix warning mentioned in #294.
v1.0.1 was tested previously as part of https://github.com/civicrm/civicrm-core/pull/25667
=> mixin-backports - Update smarty-v2 (1.0.0 => 1.0.1)

composer.json, composer.lock
This enables `civix` to run on civicrm-standalone. It brings in a newer bootstrap library from `cv.get`.
=> composer.json - Update "cv" requirement. Support "Standalone".

composer.json, composer.lock, src/CRM/CivixBundle/Services.php
This update aims to resolve an issue identified in the discussion of https://github.com/civicrm/cv/pull/166 - i.e. `civix` doesn't support some of bootstrap (initialization) options that `cv` does, which limits compatibility with some environments.
Before
---------
* When `civix` needs to acces CiviCRM, it uses `cv`'s `Bootstrap.php`.
* `Bootstrap.php` is included by way of a special/single-file download step.
* `Bootstrap.php` only supports the traditional (Civi-first / CIVICRM_SETTINGS) protocol. It doesn't support the newer (CMS-first / CIVICRM_BOOT) protocol.
After
-------
* When `civix` needs to acces CiviCRM, it uses `cv`'s `Bootstrap.php` _or_ `CmsBootstrap.php`.
* All `cv` helper classes are included as a composer dependency (`civicrm/cv-lib`).
* `civix`'s boot behavior should now …
=> Update cv library. Respect CIVICRM_BOOT or CIVICRM_SETTINGS.

box.json, build.sh, scoper.inc.php, scripts/check-phar.php, shell.nix, src/CRM/CivixBundle/Services.php
The purpose of `php-scoper` is to allow `civix.phar` to run in other environments without provoking class-conflicts. It does this by prefixing (almost all) classes.
The current configuration appears to be inert -- the final output doesn't actually have prefixes nowadays. This brings it back and adds some test-coverage.
Comments
--------------
This is very similar to https://github.com/civicrm/cv/pull/158, except that I had to do some fine-tuning on the include/exclude lists.
=> php-scoper - Fix prefixing

src/CRM/CivixBundle/Resources/views/Code/module.php.php
Neither of these commented-out functions sets a particularly good example so it ends up just being noise.
=> Remove commented-out boilerplate

scoper.inc.php
This should fix a regression where `civix.phar` fails to load on php7.
```
Fatal error: Uncaught Error: Interface 'Stringable' not found in phar:///home/cividev/bin/civix/vendor/symfony/polyfill-php80/PhpToken.php:18
Stack trace:
#0 phar:///home/cividev/bin/civix/.box/vendor/composer/ClassLoader.php(582): include()
#1 phar:///home/cividev/bin/civix/.box/vendor/composer/ClassLoader.php(433): Composer\Autoload\{closure}()
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#3 phar:///home/cividev/bin/civix/vendor/symfony/polyfill-php80/Resources/stubs/PhpToken.php(14): spl_autoload_call()
#4 phar:///home/cividev/bin/civix/.box/vendor/composer/ClassLoader.php(582): include('phar:///home/ci...')
#5 phar:///home/cividev/bin/civix/.box/vendor/composer/ClassLoader.php(433): …
```
=> Fix php-scoper rule for polyfill-80

src/CRM/CivixBundle/Resources/views/Code/form.php.php
This function is pretty prevalent in civix generated stuff - could be a mixin or core function - but probably just getting it to nice arrays etc is a step  forwards
After running it the only php grumble is it can't see that the class is called - @totten would be cool if your phpstorm extension could pick up that xml declarations make it called - but I assume that's a big lift
=> Superficial fixes to form template - hints, array syntax

src/CRM/CivixBundle/Application.php, src/CRM/CivixBundle/Builder/Content.php, src/CRM/CivixBundle/Builder/Dirs.php, src/CRM/CivixBundle/Builder/Info.php, src/CRM/CivixBundle/Builder/PhpData.php, src/CRM/CivixBundle/Builder/Template.php, src/CRM/CivixBundle/Command/AbstractCommand.php, src/CRM/CivixBundle/Command/AddManagedEntityCommand.php, tests/e2e/AddManagedEntityTest.php, tests/e2e/CivixProjectTestTrait.php
Adds a useful command which exports Afforms and managed records, leveraging the APIv4 Export action which collects sub-records into a single `.mgd.php` file (or in the case of Afforms, `.aff.php` and `.aff.html` *and* `.mgd.php`s for the search displays).
The resulting file includes `E::ts()` around translatable strings.
For a full demonstration, try exporting an existing afform, e.g.:
```
cv en civi_campaign
cd ext/civi_pledge # or any empty-ish extension
civix export Afform afsearchCampaignDashboard
```
It will write out the 2 files for the Afform plus 3 files for the 3 embedded SavedSearches into your extension (in this example `civi_pledge`), plus the navigation menu item.
=> Add `export` command for managed entities and afforms

mixin-backports.php, mixin-mods/README.md, mixin-mods/setting-admin@1.0.1.mixin.php
This adds support for `setting-admin@1` (5.68's https://github.com/civicrm/civicrm-core/pull/27569). 
To enable it, one runs:
```
civix mixin --enable=setting-admin@1
```
This creates the following behavior:
* Read `*.setting.php` for settings in this extension
* Create a permission `administer {MYEXT}`
* Create a route `civicrm/admin/{MYEXT}`
* Create a nav-item for `civicrm/admin/{MYEXT}`
I did some evaluation about version-compatibility. The original implementation of `setting-admin@1` has some  issues -- e.g. `_ts()` requires v5.64, and the chosen namespace would be problematic with the polyfill-loader (before v5.45). So I made a few updates to expand compatibility, generated a couple extensions (*with this mixin*), and spot-checked the admin-page on several versions (5.27, 5.39, …
=> Add setting-admin@1. Use some extra patches to achieve 5.27+ compatibility

src/CRM/CivixBundle/Command/AbstractCommand.php, src/CRM/CivixBundle/Upgrader.php, src/CRM/CivixBundle/Utils/Naming.php, src/CRM/CivixBundle/Utils/NamingTest.php, tests/e2e/CRMNamingTest.php, tests/e2e/CiviNamingTest.php
This is a step toward implementing `civix generate:service`.
=> Add helpers for naming classes like "Civi\MyExt\Foo"

src/CRM/CivixBundle/Command/AddManagedEntityCommand.php
Per discussion, sometimes there's a legit reason to export a managed entity that already exists.
The use-case here is that Afform autogenerates a managed entity for navigation items that belong to the form, but civix exports them as managed entities in their own right. This isn't a real conflict but civix thinks it is.
=> Export - warn but don't block exporting duplicate managed entity

src/CRM/CivixBundle/Resources/views/Code/entity-bao.php.php, src/CRM/CivixBundle/Resources/views/Code/module.php.php, src/CRM/CivixBundle/Resources/views/Code/upgrader.php.php
Not necessary because we have already taught `civilint` to ignore unused `E;`
=> Remove unnecessary phpcs comments

src/CRM/CivixBundle/Builder/Content.php, src/CRM/CivixBundle/Builder/CopyClass.php, src/CRM/CivixBundle/Builder/CopyFile.php, src/CRM/CivixBundle/Builder/CustomDataXML.php, src/CRM/CivixBundle/Builder/Ini.php, src/CRM/CivixBundle/Builder/License.php, src/CRM/CivixBundle/Builder/Mixins.php, src/CRM/CivixBundle/Builder/PHPUnitGenerateInitFiles.php, src/CRM/CivixBundle/Builder/PhpData.php, src/CRM/CivixBundle/Builder/XML.php, src/CRM/CivixBundle/Command/AbstractAddPageCommand.php, src/CRM/CivixBundle/Command/AddApiCommand.php, src/CRM/CivixBundle/Command/AddEntityBoilerplateCommand.php, src/CRM/CivixBundle/Command/AddManagedEntityCommand.php, src/CRM/CivixBundle/Command/AddTestCommand.php, src/CRM/CivixBundle/Command/AddUpgraderCommand.php, src/CRM/CivixBundle/Command/Mgd.php, src/CRM/CivixBundle/Command/UpgradeCommand.php, src/CRM/CivixBundle/Upgrader.php, src/CRM/CivixBundle/Utils/Files.php, src/CRM/CivixBundle/Utils/Path.php
Reorganize the `export` command. Fix a bug with re-exporting existing files.
Move helper functions from `AddManagedEntityCommand` to `Upgrader`
This is a stylistic change and a functional fix.
* The stylistic issue is that civix currently has two code-styles in the code-generation logic.
* (*older*) Most of the `generate:xxx` commands work with `CRM\CivixBundle\Builder\*` classes (with an OOP hierarchy). 
* (*newer*) Most of the auto-upgrade steps (`upgrade/*.up.php`) use `CRM\CivixBundle\Upgrade::*`  functions.
* When working on the upgrade-steps, I found it a bit tedious to use the `Builder` contract for everything.
* The basic advantages of the newer style are: (1) it has access to more utilities (`$this->infoXml`, `$this->io`, and so on*), (2) it's easier to incorporate …
=> "export" - Convert to helper-style. Refine afform exports. Prettier console messages.

phpunit.xml.dist, src/CRM/CivixBundle/CivixTestListener.php, src/CRM/CivixBundle/Command/AbstractCommand.php, src/CRM/CivixBundle/Command/AddManagedEntityCommand.php, src/CRM/CivixBundle/Command/AddServiceCommand.php, src/CRM/CivixBundle/Command/UpgradeCommand.php, src/CRM/CivixBundle/Generator.php, src/Civix.php, tests/e2e/CRMNamingTest.php, tests/e2e/CiviNamingTest.php, tests/e2e/CivixProjectTestTrait.php, upgrades/16.10.0.up.php, upgrades/19.06.2.up.php, upgrades/20.06.0.up.php, upgrades/22.05.0.up.php, upgrades/22.05.2.up.php, upgrades/22.10.0.up.php, upgrades/22.12.1.up.php, upgrades/23.01.0.up.php, upgrades/23.02.0.up.php, upgrades/23.02.1.up.php
Overview
---------
Take the existing `Upgrader` concept and convert it to a more general `Generator` concept.
Motivation
-----------
1. It can be used for generating new code *or* generating upgraded code.
2. It's confusing to use the same word ("Upgrader") to describe both (a) the thing inside civix that manipulates ext-code and (b) the thing inside an ext that manipulates DB schema.
Change
-------
* __Before__: Various calls to `new Upgrader(...)` and/or `$this->getUpgrader()`
* __After__: Various calls to `Civix::generator()`
=> (REF) Convert "Upgrader" to "Generator"

src/CRM/CivixBundle/Command/AddEntityBoilerplateCommand.php
This supports https://github.com/civicrm/civicrm-core/pull/28827 by adding the extra bit of info it needs.
=> Add FKColumnName to fields metadata

mixin-backports.php, src/CRM/CivixBundle/Builder/Mixins.php
Overview
------------
As of Civi 5.71 (https://github.com/civicrm/civicrm-core/pull/29187), the `smarty-v2` mixin has a new name: `smarty`. Because... it's not necessarily Smarty v2. Both names will continue to work in the same way. However, we should start encouraging the new name.
Before
--------
Whenever `civix` activates Smarty support, it uses `smarty-v2@1.x.x`.
After
------
Whenever `civix` activates Smarty support, it checks the compatibility (eg `<ver>5.50</ver>` or `<ver>5.75</ver>`). If the target is 5.71+, then it will prefer the new name.
Comments
--------------
There's a trade-off in how one does this:
* We could do a straight rule to switch all ext's to `smarty@`. This will push the newer name sooner... but you're more likely to get backport files …
=> Smarty Substitution - Recommend 'smarty@1' or 'smarty-v2@1' depending on environment

src/CRM/CivixBundle/Application.php, src/CRM/CivixBundle/Builder/PhpData.php, src/CRM/CivixBundle/Command/ConvertEntityCommand.php
Adds command to convert entities from legacy xml/schema to current .entityType.php format.
Used to generate the `entityType.php` files in https://github.com/civicrm/civicrm-core/pull/29472
=> Add convert-entity command

mixin-backports.php
Adds new mixin from https://github.com/civicrm/civicrm-core/pull/29771
=> Add entity-types-php@2

src/CRM/CivixBundle/Command/ConvertEntityCommand.php
~~Three~~ 4 fixes to the entity generation, used to fix the test failures in https://github.com/civicrm/civicrm-core/pull/29991
This fixes discrepancies between the old core/CodeGen and the new civix/convert-entity output.
=> Convert-entity - 4 fixes

mixin-backports.php
Update to reflect the pending update in https://github.com/civicrm/civicrm-core/pull/30148
Note: The existing 'minimum' was '5.27'. I re-tested that version locally, and Smarty still worked fine.
cc @colemanw
=> mixin-backports - Update smarty adapters to v1.0.2

nix/buildkit.nix, shell.nix
This should address a compatibility issue on Windows/PHP 8.3
=> Generate civix.phar on box 4.6.1

src/CRM/CivixBundle/Command/ConvertEntityCommand.php
Followup to #342
Now the `convert-entity` command will add the appropriate mixin, and delete old `entityType.php` files which could be potentially problematic if we left them hanging around.
=> Switch mixin after ConvertEntity

src/CRM/CivixBundle/Builder/Info.php
I don't think `http` is still widely used for these links (or for any other link nowadays).
=> info.xml: change http to https in <urls>

mixin-backports.php
Port https://github.com/civicrm/civicrm-core/pull/30281
=> mixin-backports - Update smarty adapters to v1.0.3

composer.json, composer.lock, src/CRM/CivixBundle/Builder/PhpData.php
* Use structured mechanisms to target/format elements in the data tree
* Closes the loopholes that arise from regex
* Supports either `fn() => ...` (php>=7.4) or `function(){ ... }` (php<7.4)
=> PhpData - Use structured document instead of regex

src/CRM/CivixBundle/Command/AbstractCommand.php, src/CRM/CivixBundle/Command/AddAngularDirectiveCommand.php, src/CRM/CivixBundle/Command/AddAngularPageCommand.php, src/CRM/CivixBundle/Command/AddCustomDataCommand.php, src/CRM/CivixBundle/Command/AddEntityBoilerplateCommand.php, src/CRM/CivixBundle/Command/AddEntityCommand.php, src/CRM/CivixBundle/Command/AddTestCommand.php, src/CRM/CivixBundle/Command/AddUpgraderCommand.php, src/CRM/CivixBundle/Command/BuildCommand.php
All of these commands use the helper `assertCurrentFormat()`. Among other things, that helper asserts that the extension-type is 'module'.
So these checks are redundant.
=> Drop redundant assertions

src/CRM/CivixBundle/Builder/Info.php
I would like to recommend that people use `x.y.z` as versions numbers, instead of `x.y`. For now, it's just a recommendation. It makes it easier use composer (which requires semantic versioning).
Related discussion:
- https://lab.civicrm.org/documentation/docs/dev/-/merge_requests/1197#note_170192
- https://lab.civicrm.org/infra/extdir/-/issues/7
=> Default to version 1.0.0 instead of 1.0

src/CRM/CivixBundle/Command/ConvertEntityCommand.php
The companion to https://github.com/civicrm/civicrm-core/pull/30476
=> ConvertEntity - Don't write maxlength, it's redundant

src/CRM/CivixBundle/Resources/views/Code/api.php.php, src/CRM/CivixBundle/Resources/views/Code/entity-api.php.php
Prior to CiviCRM 5.52 we threw a mismash of these extensions. They all had to work everywhere because it was unpredictable. In 5.52 we made the API_Exception and CiviCRM_Api3_Exception aliases of CRM_Core_Exception. However, on the off chance people are creating extensions for really old civi versions with the latest civix it would still be handled on those older versions (we were always throwing CRM_Core_Exception all over the show)
=> Update references from extension aliases to the CRM_Core_Extension

src/CRM/CivixBundle/Utils/NamingTest.php, src/CRM/CivixBundle/Utils/Path.php, src/CRM/CivixBundle/Utils/PathTest.php
As reported by loren-bm on ([Mattermost](https://chat.civicrm.org/civicrm/pl/ruo9km1w4idz7mh34jczhpeirr)), there's a recent regression when running `civix upgrade` on Windows:
```
Executing upgrade script phar://E:/d10/vendor/civicrm/cli-tools/extern/civix.phar/upgrades\24.09.0.up.php
In Checker.php line 55:
[RuntimeException]
Unrecognized library: civimix-schema@5
```
The underlying problem involves the switch to `Webmozart\Glob` -- @demeritcowboy found that it expects to have paths normalized using `/`. This is not entirely unusual. Symfony Filesystem v5.4+ has a [similar normalization policy](https://github.com/symfony/filesystem/blob/7.0/Path.php#L114-L117).
This revision *should* fix the error. The approach is a little more aggressive, in that it flip-flips on the approach to …
=> Paths - On Windows, normalize to forward-slash

src/CRM/CivixBundle/Resources/views/Code/module.civix.php.php
When using `generate:upgrader` for new-style upgrader-class, it should always be installable, even if... there are no EFv2 entities. 
Example use case (on 5.78+)
```bash
civibuild restore dmaster
civix generate:module testupgrader --enable=no --no-interaction
cd testupgrader
civix generate:upgrader ## NOTE: No new entities!
cv en testupgrader
```
=> generate:upgrader - New-style upgrader-class should always be installable, even if... (Option A)

src/CRM/CivixBundle/Builder/Info.php
=> Handle dynamic versions

src/CRM/CivixBundle/Builder/PhpData.php
`PhpData::save` generates strange output from the input data on PHP<8.0.0.
For example during `convert-entity` command:
If the legacy xml entity files contains `<import>` or `<export>` elements in a `<field>` element
```
<field>
...
<import>true</import>
<export>true</export>
...
</field>
```
will be converted in the generated `.entityType.php` to
```
'usage' => [
constant(fn() => 'import'),
'export',
'duplicate_matching',
],
```
which emits a PHP WARNING when evaluated.
This is due to loose type checking in `in_array()` in PHP prior to 8.0.0
This PR adds strict type checking to `in_array()`.
=> \CRM\CivixBundle\Builder\PhpData::save set strict flag on in_array

upgrades/24.09.1.up.php
If an extension has no Upgrader defined in `info.xml`, this upgrade step will tell that:
```
Update info.xml to use CiviMix\Schema\{MyExtension}\AutomaticUpgrader
```
but it won't do it.
It's just confusing for the user.
In this PR, the displayed planned actions are matched to the actual ones.
=> upgrades/24.09.01: only add step to update Upgrader if there is an Upgrader

src/CRM/CivixBundle/Command/ConvertEntityCommand.php, upgrades/24.09.1.up.php
`\CRM\CivixBundle\Command\ConvertEntityCommand::convertEntities()` is called regardless if there are actual legacy xml entities to convert, and it adds the `entity-types-php@2` unconditionally.
In this PR, `convertEntities` is called only if there are files to convert. Also a check is 
added to `convertEntities` to return early if it's called with no xml files.
fixes #372
=> upgrade/24.09.1, convert-entity: adds entity-types-php@2 mixin even the extension doesn't define new entities

src/CRM/CivixBundle/Checker.php, src/CRM/CivixBundle/Parse/PrimitiveFunctionVisitor.php, src/CRM/CivixBundle/Parse/PrimitiveFunctionVisitorTest.php, src/CRM/CivixBundle/Parse/Token.php, src/CRM/CivixBundle/Utils/PrimitiveFunctionVisitor.php, upgrades/25.01.0.up.php
Overview
-------------
"Entity Framework v1" (EFv1) developed gradually over time. If you search `universe`, you will find at least 3 patterns for how entities have been registered, including:
1. Using mixin `entity-types-php@1` (which reads from `xml/schema/**.entityType.php`)
2. Using boilerplate function `_MYNAME_civix_civicrm_entityTypes` (which also reads from `xml/schema/**.entityType.php`)
3. Using static declarations or custom logic in `hook_civicrm_entityTypes`
The upgrader routine in 24.09.1 is generally geared toward the first two.
When I ran `civix upgrade` on Mosaico, I found it landed in that last set -- it has a [non-trivial implementation of hook_civicrm_entityTypes](https://github.com/veda-consulting-company/uk.co.vedaconsulting.mosaico/blob/3.6/mosaico.php#L261-L271). …
=> EFv2 - When upgrading from EFv1, check for conflicting hooks

src/CRM/CivixBundle/Utils/MixinLibraries.php, upgrades/25.01.1.up.php
Overview
---------
Improve compatibility with Backdrop. Note that:
* Backdrop CLI allows you to read PHAR files. So automated `civix` testing with `civimix-schema@XX.phar` had passed on Backdrop. ___Great, but...___
* Backdrop Web UI [completely blocks usage of PHAR files](https://github.com/backdrop/backdrop/blob/1.29.x/core/includes/bootstrap.inc#L768-L770). 🤦 
Switching from PHAR to subdirectory works-around it.
Before
-------
When using EFv2 with civimix-schema@5, the backport is created as a PHAR file.
After
-------
When using EFv2 with civimix-schema@5, the backport is created as a subdirectory.
=> Convert civimix-schema@5 from PHAR to subdir

src/CRM/CivixBundle/Utils/Formatting.php, upgrades/24.09.1.up.php, upgrades/25.01.0.up.php
The main update here addresses #384. It presents a summary about the pre-existing EFv1 data and conditionally warns if this looks inconsistent.
=> EFv2 Tweaks - Warn if EFv1 had a mismatched entity list (#384)

src/CRM/CivixBundle/Resources/views/Code/entity-dao.php.php, src/CRM/CivixBundle/Resources/views/Code/module.civix.php.php
Before
------
```
FILE: ...alone-clean/web/core/ext/user_dashboard/user_dashboard.civix.php
----------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
----------------------------------------------------------------------
76 | ERROR | [x] Expected 1 blank line after function; 2 found
79 | ERROR | [x] The closing brace for the class must have an empty
|       |     line before it
----------------------------------------------------------------------
PHPCBF CAN FIX THE 2 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------
```
And 
```
FILE: ...build-2/web/src/ext/oauth-client/CRM/OAuth/DAO/OAuthSysToken.php
----------------------------------------------------------------------
FOUND 15 …
```
=> Fix civilint whitespace errors

src/CRM/CivixBundle/Builder/Info.php, src/CRM/CivixBundle/Resources/views/Code/upgrader.php.php
When running the command `civix generate:upgrader` on a core ext, I noticed two problems:
1. The compatability version was downgraded.
2. There was a linting error in the generated file.
Fixed 1 by teaching the function `raiseCompatibilityMinimum` to [work with the '[civicrm.majorVersion]' token](https://github.com/totten/civix/pull/376).
Fixed 2 by adding a newline after the `use` statement
=> Upgrader - Fix core version downgrading & linting error

src/CRM/CivixBundle/Command/AbstractCommand.php, src/CRM/CivixBundle/Command/InitCommand.php
Overview
-------------
Address the inconsistent behavior of `--yes` by using the (more consistent) option `--no-interaction`.
Fix #391
Before
---------
* `civix` inherits the option `--no-interaction` (`-n`) from Symfony Console.
* `civix` also defines the option `--yes`, but this is only used for 1-2 prompts. Most prompts ignore it.
* (*I suspect it lost a lot relevance when logic was migrated from `Command` classes to the `Generator`.*)
After
------
* `civix` inherits the option `--no-interaction` (`-n`) from Symfony Console.
* `civix --yes` is a deprecated alias for `civix --no-interaction`.
=> Merge `--yes` with the more conventional `--no-interaction`

src/CRM/CivixBundle/Command/AddApiCommand.php, src/CRM/CivixBundle/Command/MixinCommand.php, src/CRM/CivixBundle/Generator.php, src/CRM/CivixBundle/Utils/CivixStyle.php, src/CRM/CivixBundle/Utils/IOStack.php, upgrades/19.06.2.up.php, upgrades/20.06.0.up.php, upgrades/22.05.0.up.php, upgrades/22.05.2.up.php, upgrades/22.10.0.up.php, upgrades/23.01.0.up.php, upgrades/23.02.1.up.php
`symfony/console` defines a general helper `OutputStyle` (combination of the traditional/lower-tech `OutputInterface` and the newer/more-semantic `StyleInterface`). And it defines a specific implementation of this helper, `SymfonyStyle`.
In a draft to address #391, it was useful to be able override/extend `SymfonyStyle`. We ultimately didn't need that draft, but I think the refactoring there is "better in than out".
=> (REF) Relax coupling to SymfonyStyle

scripts/run-tests.sh, tests/e2e/CivixProjectTestTrait.php
This will make it easier for the test-matrix to include E2E tests of the PHAR build.
This parallels the options in `scripts/make-snapshots.sh` (although the flag-name is slightly different -- most options for `run-tests.sh` are supposed to pass-through to `phpunit`, but these options don't).
=> scripts/run-tests.sh - Accept option --civix-phar and --civix-src

src/CRM/CivixBundle/Command/InspectFunctionCommand.php, src/CRM/CivixBundle/Parse/ParseException.php, src/CRM/CivixBundle/Parse/PrimitiveFunctionVisitor.php, src/CRM/CivixBundle/Parse/PrimitiveFunctionVisitorTest.php, src/CRM/CivixBundle/Parse/Token.php
Consider this command:
```
civix inspect:fun --code=/foo/ my_folder
```
Before, it would fail on `my_folder`. Now, it recurses.
When doing a recursive search on `universe`, it encountered more edge-cases where parsing failed. Fix the fixable cases; and for the others, display better warnings/errors.
=> civix inspect:fun - Add recursion and more guards

src/CRM/CivixBundle/Checker.php
civix will include or exclude a compatiblity-file (`pathload-0.php`) depending on the target version of CiviCRM. The PR fixes a slight misalignment on the boundary.
| | `<ver>5.72</ver>`| `<ver>5.73</ver>`| `<ver>5.74</ver>` |
| -- | -- | -- | -- |
| Before (Incorrect) | Include compat file | Exclude compat file | Exclude compat file |
| After (Correct) | Include compat file | __Include compat file__ | Exclude compat file |
Presumably, the corresponding update for civicrm-core was drafted during development of 5.73 -- but was actually merged into 5.74.
=> Pathload is provided by civicrm-core@5.74 (not 5.73)

src/CRM/CivixBundle/Generator.php
I made up the word pretruncated.
In https://github.com/totten/civix/pull/355 it added a use of `$ctx['fullName']` to name the test suite, but it seems like maybe this never worked unless it was also building the info.xml at the same time as making phpunit.xml?
This PR updates it to load it from the info since fullName never gets set.
e.g. At the time this was the code and you can see here fullName is never set: https://github.com/totten/civix/blob/fb21c7f4ac2c0e8786a16a73b733ab83b3cdc625/src/CRM/CivixBundle/Command/AddTestCommand.php#L60-L73
And in the current code the "generator" only has access to the "default ctx", and not this ctx, which also doesn't have fullName anyway:
* https://github.com/totten/civix/blob/b4c7e5fe832cb88a91b503a6f7ea436e7637f749/src/CRM/CivixBundle/Command/AddTest …
=> generate:api gives error and stops before creating phpunit.xml. Similarly generate:test gives a warning and the test suite name is pretruncated.

src/CRM/CivixBundle/Builder/Info.php
@totten basic version of adding php_compatibility & smarty_compatibilty tags on civix:generate 
I'm now hitting the issue where I'm dropping php 8.0 support in extensions because the versions of packages that work with 8.0 conflict with drupal versions of the same package - obviously there are multiple issues in play here but my specific concern is that there is limited visibility on extensions not supporting the php or smarty version that is in use. To be able to block downloads or pro-actively warn people we need more extensions to specify the version in play - so I think the first focus is
- civix generate
- civix upgrade
- core extensions
Note I've been deliberately forward-looking with Smarty - I don't see people specifying support for older smarty versions being particularly …
=> Add smarty compatibility and php_compatibility tags on civix generate

src/CRM/CivixBundle/Command/AddEntityCommand.php
This used to be a soft-requirement but is now strongly encouraged.
- See https://github.com/civicrm/civicrm-core/pull/33371
- See https://github.com/totten/civix/pull/412
=> Add scan-classes mixin when adding Api4 classes

README.md, composer.json, composer.lock
In the test-suite for civix, the oldest target is ESR `-2` (i.e. going back a couple ESR cycles). After 6.4 went ESR, that means the oldest config is now PHP 7.4.
```php
$it_s = fn($in) => "the future";
```
=> Bump PHP minimum (7.3 => 7.4)

src/CRM/CivixBundle/Builder/Info.php, src/CRM/CivixBundle/Checker.php, src/CRM/CivixBundle/Command/InitCommand.php, src/CRM/CivixBundle/Parse/PrimitiveFunctionVisitor.php, upgrades/25.10.0.up.php, upgrades/25.10.1.up.php
Overview
-------------
The class-scanner allows you to create new PHP files with services and listeners -- without needing to hand-edit or re-generate the main `*.php` files. This encourages modular development, and it makes it easier to copy/borrow/move snippets of code. The PR encourages adoption with main two revisions:
1. `civix generate:module`: On CiviCRM v5.51+, enable `scan-classes@1` by default for new extensions.
2. `civix upgrade`: Prompt the developer to enable the scanner. Include the known counter-indicators (*i.e. exceptions where you may not want it*) and alternatives (*e.g. custom scanner*).
This is generally an outgrowth of work on https://github.com/civicrm/civicrm-core/pull/33371, and it aligns with @ufundo's argument (*which I mostly agree with*) that class-scanning …
=> Class Scanner - Recommend general adoption
