src/CRM/CivixBundle/Resources/views/Code/module.civix.php.php

These are all changes to reduce phpcs warnings

Phpcs changes

---

src/CRM/CivixBundle/Resources/views/Code/module.php.php

Here is the stub per last comment - don't have more at the moment but perhaps others will add them too.

Add stub function (commented out) to assist module writers

---

src/CRM/CivixBundle/Resources/views/Code/api.php.php
src/CRM/CivixBundle/Resources/views/Code/entity-api.php.php

URL corrections

---

src/CRM/CivixBundle/Resources/views/Code/upgrader-base.php.php

Support for multilingual upgrade in civicrm extension #77

---

tests/make-example.sh

add some comments and clarify script actions

---

src/CRM/CivixBundle/Resources/views/Code/form.php.php
src/CRM/CivixBundle/Resources/views/Code/page.php.php
src/CRM/CivixBundle/Resources/views/Code/upgrader-base.php.php

These haven't been necessary in quite a long time.

Remove non-required requires

---

src/CRM/CivixBundle/Command/AddTestCommand.php
src/CRM/CivixBundle/Resources/views/Code/test-phpunit.php.php
tests/make-example.sh

PR for general PHP Unittest integration in Civix
* Add template 'phpunit'
* Add example test to civix test script

Add "generate:test --template=phpunit" for minimalist test

---

src/CRM/CivixBundle/Builder/PHPUnitGenerateInitFiles.php
src/CRM/CivixBundle/Command/AddApiCommand.php
src/CRM/CivixBundle/Command/AddTestCommand.php
src/CRM/CivixBundle/Resources/views/Code/phpunit-boot-cv.php.php
src/CRM/CivixBundle/Resources/views/Code/test-api.php.php

PR to automatically add unittest file generation upon generating an API command

When creating a new API, automatically create a unit test.

---

src/CRM/CivixBundle/Resources/views/Code/module.civix.php.php
src/CRM/CivixBundle/Resources/views/Code/module.php.php

See also https://github.com/civicrm/civicrm-dev-docs/pull/490

Improved usage instructions for navMenu hooks

---

src/CRM/CivixBundle/Resources/views/Code/entity-schema.xml.php

I thought this might be a reasonable way of getting an appropriate version for the xml file.

(Un)set version in entity XML templates

---

src/CRM/CivixBundle/Command/AddEntityCommand.php

The following output more clearly directs the user as to appropriate next steps.

More helpful output for generate:entity command

---

src/CRM/CivixBundle/Builder/Info.php

arguably this should be 5.3 as earlier versions will be insecure

Bump default version to 5.0

---

src/CRM/CivixBundle/Resources/views/Code/report.php.php

Improve template to reflect recommended practice - ie. don't override main select, where order by functions but use specific field overrides instead. Allow built in group by & order by to work by default.

Update report php template

---

src/CRM/CivixBundle/Command/AddAngularModuleCommand.php
src/CRM/CivixBundle/Resources/views/Code/angular-module.js.php

Before
----
Requirements declared in js
After
------
Requirements declared in php

Use helper function for angular module requirements

---

src/CRM/CivixBundle/Resources/views/Code/test-api.php.php
src/CRM/CivixBundle/Resources/views/Code/test-e2e.php.php
src/CRM/CivixBundle/Resources/views/Code/test-headless.php.php
src/CRM/CivixBundle/Resources/views/Code/test-phpunit.php.php
src/CRM/CivixBundle/Utils/NamingTest.php

This code should be compatiable to phpunit5.7 as well as phpunit6
ping @eileenmcnaughton @totten

Update code standard from phpunit4/5 to phpunit5/6

---

src/CRM/CivixBundle/Command/AddAngularDirectiveCommand.php
src/CRM/CivixBundle/Command/AddAngularPageCommand.php

AddAngular*Command - Fix ts domain

---

src/CRM/CivixBundle/Builder/Info.php
src/CRM/CivixBundle/Command/AddEntityCommand.php
src/CRM/CivixBundle/Resources/views/Code/entity-api4.php.php
tests/make-example.sh

This adds an api4 file to expose new civix entities to api v4.

Add api4 file when creating an entity

---

src/CRM/CivixBundle/Command/AddEntityBoilerplateCommand.php

This is a resubmit following rebase of #134

generate foreign keys in DAOs

---

src/CRM/CivixBundle/Resources/views/Code/api.php.php

This is the little change I promised to offer to make!
I think the diff is small enough to explain more clearly than I could in words

Replace NewEntity and NewAction with the names of that being generated

---

composer.json

Updated Symfony components so requirements for composer are met.

Updated Symfony components

---

src/CRM/CivixBundle/Resources/views/Code/module.php.php
src/CRM/CivixBundle/Resources/views/Code/phpunit-boot-cv.php.php
src/CRM/CivixBundle/Resources/views/Code/upgrader-base.php.php
src/CRM/CivixBundle/Resources/views/Code/upgrader.php.php

ping @eileenmcnaughton @totten

Fix style on commenting out of code

---

src/CRM/CivixBundle/Resources/views/Code/upgrader-base.php.php

Fixes some style issues caught by jenkins and some other ones I noticed in upgrader-base.php

NFC - Style fixes

---

src/CRM/CivixBundle/Resources/views/Code/angular-page.html.php
src/CRM/CivixBundle/Resources/views/Code/angular-page.js.php

This is a reviewers cut of #154 - I've tested it out and confirm the new code works.

Use controllerAs for angular best-practice

---

UPGRADE.md
src/CRM/CivixBundle/Resources/views/Code/entity-api.php.php

See: https://chat.civicrm.org/civicrm/pl/9pf1exq3ypn9ujj153m8tqpkor
@totten @twomice

generate:entity - APIv3 "get"ter returns incorrect array

---

README.md

Updates the readme to reflect current requirements.

Update system requirements in readme

---

src/CRM/CivixBundle/Command/AddEntityBoilerplateCommand.php

Fix for #217: Add ENGINE=InnoDb to Entity Boilerplate command

---

src/CRM/CivixBundle/Resources/views/Code/upgrader.php.php

This will help when diagnosing a fairly common gotcha - ie forgetting to return TRUE.
Currently there are very few clues as to when that is the case - so if these
type hints become part of the copy & paste it will help with that
@ejegg

Add typing to upgrader functions

---

src/CRM/CivixBundle/Resources/views/Code/module.php.php

Updates boilerplate hook comments in module files.

NFC - Update hook comments in module file

---

bin/var-dump-server
composer.lock

I wasn't finding composer install was working because I guess the lock file was out of date. I ran a generic composer update & it also added a bin file in the symfony folder.

Run composer update

---

composer.json

Updated Symfony components so requirements for composer are met.

refs #composer updated Symfony components (^5)

---

src/CRM/CivixBundle/Command/AddEntityBoilerplateCommand.php

Overview
----------
This aims to address the errors outputted by `generate:entity-boilerplate` command (as reported by @rbaugh in #249). Errors are reproducible on php80+WordPress (with more steps described in #249). The errors indicate that some configuration-options are unavailable. The patch provides the missing options.
cc @seamuslee001 @eileenmcnaughton as it re-raises some the utf8mb4/extension questions.
Background
------------
The command `generate:entity-boilerplate` calls the SQL code-generator provided by core (ie `civicrm-core:CRM/CodeGen`). In core, the equivalent process reads [xml/schema/Schema.xml](https://github.com/civicrm/civicrm-core/blob/5.51.1/xml/schema/Schema.xml) which defines some general options/defaults for SQL tables, eg
```xml
<database …
```

AddEntityBoilerplateCommand - Fill in the `$config->database` properties

---

src/CRM/CivixBundle/Resources/views/Code/upgrader.php.php

Use fruit as examples instead of a wanker which is a bit more PC.

Use fruit as examples instead of a wanker

---

src/CRM/CivixBundle/Builder/Mixins.php
src/CRM/CivixBundle/UpgradeList.php

Sorta like https://github.com/civicrm/civicrm-core/pull/24948 but for civix

Use 2nd argument of basename instead of preg_replace

---

scripts/load-snapshot.sh
src/CRM/CivixBundle/Upgrader.php

civix upgrade - Fix warning about preg_match() on php81

---

src/CRM/CivixBundle/Resources/views/Code/module.civix.php.php

Changes per https://github.com/civicrm/civicrm-core/pull/25249

Update Smarty code to use `addTemplateDir`

---

mixin-backports.php
src/CRM/CivixBundle/Command/AbstractAddPageCommand.php
src/CRM/CivixBundle/Command/InitCommand.php
src/CRM/CivixBundle/Resources/views/Code/module.civix.php.php
tests/e2e/SnapshotUpgradeTest.php
upgrades/23.01.0.up.php

Corollary to https://github.com/civicrm/civicrm-core/pull/25369

Use 'smarty-v2' mixin

---

src/CRM/CivixBundle/Resources/views/Code/module.civix.php.php

Kill off CRM_Utils_Array::value

---

composer.json
composer.lock

See discussion on https://github.com/totten/civix/pull/300

composer.json - Update to civicrm/cv-lib v0.3.45

---

README.md
build.sh
scripts/build.sh
scripts/make-snapshots.sh
scripts/releaser.php
shell.nix

* Move `build.sh` to `./scripts/`
* Add `releaser.php` to `./scripts/`
* Simplify `build.sh`
* For `shell.nix` build-environment, use components from buildkit
* Update README to encourage `nix-shell` for compilation

Multiple toolchain updates

---

src/CRM/CivixBundle/Command/AddAngularDirectiveCommand.php
src/CRM/CivixBundle/Command/AddAngularModuleCommand.php
src/CRM/CivixBundle/Command/AddAngularPageCommand.php

Our Angular boilerplate really needs some work, but short of that here's some simple comment cleanup.

Update comments about Angular modules

---

scripts/run-tests.sh
src/CRM/CivixBundle/Command/InitCommand.php
src/CRM/CivixBundle/Utils/AutoCleanup.php
src/CRM/CivixBundle/Utils/Files.php
src/CRM/CivixBundle/Utils/Formatting.php
src/Civix.php
tests/e2e/CivixProjectTestTrait.php

These are small extractions from #331. They should have little effect on runtime behavior, but will help make the other PR smaller.

Misc - Sundry tweaks and fixes

---

composer.lock

It seems like the cv here should be the same version as cv.

Update cv-lib version to match cv's version

---

src/CRM/CivixBundle/Builder/Info.php
tests/e2e/MixinMgmtTest.php

info.xml: change <maintainer> to <authors>

---

src/CRM/CivixBundle/Command/ConvertEntityCommand.php

Fix bug in #347 - Forgot to save info.xml after updating mixins

---

src/CRM/CivixBundle/Builder/PhpUnitXML.php

Overview
--------
Tests are no longer all mine.
Before
------
"My Test Suite"
After
-------
"afform_core Tests"

Give the test suite a name

---

src/CRM/CivixBundle/Command/ConvertEntityCommand.php

Just makes more sense this way.

Convert $attributes['multiple'] to boolean

---

src/CRM/CivixBundle/Command/ConvertEntityCommand.php
src/CRM/CivixBundle/Generator.php
src/CRM/CivixBundle/Resources/views/Code/entity-dao.php.php

This adds the nicety of `@property` annotations in the converted DAO classes, and updates a few code comments.

ConvertEntity - Add @property annotations, update comments

---

composer.lock

`totten/license-data` got a new release (0.3) recently, update dependency here

composer: update totten/license-data

---

src/CRM/CivixBundle/Command/ConvertEntityCommand.php

Pairs well with https://github.com/civicrm/civicrm-core/pull/31178

ConvertEntity - Format pseudoconstant.callback nicely

---

src/CRM/CivixBundle/Generator.php

Before
------
```
Warning: Undefined array key "search_displays" in ../CRM/CivixBundle/Generator.php on line 316
```
After
------
Fixed

Export: Fix undefined index error

---

mixin-backports.php

https://github.com/totten/civix/issues/334

Use newer mixin/polyfill.php (fix linter warning)

---

src/CRM/CivixBundle/Command/AddEntityCommand.php
src/CRM/CivixBundle/Command/AddManagedEntityCommand.php
src/CRM/CivixBundle/Command/AddThemeCommand.php

When will they stop being experimental?

---

src/CRM/CivixBundle/Utils/MixinLibraries.php

This should fix a regression (#395) from #387. The regression arises when using a `civix.phar`-build to generate entities.

MixinLibraries - Fix extraction of nested data 
